import { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import PublicNavbar from '../components/PublicNavbar';
import PublicFooter from '../components/PublicFooter';
import {
  Sparkles,
  FileText,
  Shield,
  Zap,
  History,
  ArrowRight,
  Users,
  CheckCircle2,
  Star,
  Clock,
  Globe,
  Download,
  Brain,
  Lock,
  PieChart,
  Share2,
} from 'lucide-react';

const BRAND = '#714B67';

/* ─── Tiny reusable components ─────────────────────────────── */

const Pill = ({ children }: { children: React.ReactNode }) => (
  <span
    className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold uppercase tracking-wider"
    style={{ backgroundColor: `${BRAND}12`, color: BRAND }}
  >
    {children}
  </span>
);

const FeatureCard = ({
  icon: Icon,
  title,
  desc,
  accent = false,
}: {
  icon: any; title: string; desc: string; accent?: boolean;
}) => (
  <div
    className={`p-6 rounded-2xl border flex flex-col gap-4 transition-all hover:-translate-y-0.5 hover:shadow-lg ${
      accent ? 'text-white border-transparent' : 'bg-white border-gray-100 shadow-sm'
    }`}
    style={accent ? { backgroundColor: BRAND } : {}}
  >
    <div
      className="w-10 h-10 rounded-xl flex items-center justify-center"
      style={accent ? { backgroundColor: 'rgba(255,255,255,0.15)' } : { backgroundColor: `${BRAND}12`, color: BRAND }}
    >
      <Icon size={20} />
    </div>
    <div>
      <h3 className={`font-semibold text-base mb-1 ${accent ? 'text-white' : 'text-gray-900'}`}>{title}</h3>
      <p className={`text-sm leading-relaxed ${accent ? 'text-white/70' : 'text-gray-500'}`}>{desc}</p>
    </div>
  </div>
);

const Step = ({ n, title, desc }: { n: number; title: string; desc: string }) => (
  <div className="flex gap-4">
    <div
      className="w-8 h-8 rounded-lg flex items-center justify-center font-bold text-sm text-white shrink-0 mt-0.5"
      style={{ backgroundColor: BRAND }}
    >
      {n}
    </div>
    <div>
      <p className="font-semibold text-gray-900 text-sm">{title}</p>
      <p className="text-gray-500 text-sm mt-0.5">{desc}</p>
    </div>
  </div>
);

const Avatar = ({ initials, color }: { initials: string; color: string }) => (
  <div className="w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold border-2 border-white" style={{ backgroundColor: color }}>
    {initials}
  </div>
);

/* ─── Main Component ───────────────────────────────────────── */

const LandingPage = () => {
  return (
    <div className="min-h-screen bg-white text-gray-900 overflow-x-hidden">
      <PublicNavbar />

      {/* ── Hero ─────────────────────────────────────── */}
      <section className="relative pt-28 pb-20 px-4 overflow-hidden">
        {/* Background */}
        <div className="absolute inset-0 -z-10 pointer-events-none">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[900px] h-[500px] rounded-full opacity-20 blur-[120px]" style={{ background: `radial-gradient(circle, ${BRAND} 0%, transparent 70%)` }} />
        </div>

        <div className="max-w-5xl mx-auto text-center">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 bg-white border border-gray-100 rounded-full px-4 py-1.5 shadow-sm mb-8">
            <div className="flex -space-x-1.5">
              <Avatar initials="DK" color="#714B67" />
              <Avatar initials="SR" color="#9C6B8A" />
              <Avatar initials="VN" color="#5A3D52" />
            </div>
            <span className="text-xs text-gray-500">Trusted by <strong className="text-gray-800">2,500+</strong> teams</span>
            <span className="w-px h-3 bg-gray-200" />
            <Pill><Sparkles size={10} />Gemini 2.5</Pill>
          </div>

          {/* Headline */}
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight text-gray-900 mb-5 leading-tight">
            Professional documents,<br />
            <span style={{ color: BRAND }}>generated by AI</span> in seconds.
          </h1>

          <p className="text-lg text-gray-500 max-w-2xl mx-auto mb-8 leading-relaxed">
            DocuFlow AI turns plain‑text briefs into polished quotations, invoices, proposals, and more — complete with your branding and ready-to-send PDFs.
          </p>

          {/* CTA buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3 mb-14">
            <Link
              to="/register"
              style={{ backgroundColor: BRAND }}
              className="px-7 py-3 text-white rounded-xl font-semibold text-sm hover:opacity-90 transition-all shadow-lg flex items-center gap-2 group"
            >
              Start for free
              <ArrowRight size={16} className="group-hover:translate-x-0.5 transition-transform" />
            </Link>
            <a
              href="#features"
              className="px-7 py-3 border border-gray-200 text-gray-700 rounded-xl font-semibold text-sm hover:bg-gray-50 transition-all"
            >
              See how it works
            </a>
          </div>

          {/* App mockup */}
          <div className="bg-white rounded-2xl border border-gray-200 shadow-2xl overflow-hidden max-w-4xl mx-auto">
            {/* Browser chrome */}
            <div className="bg-gray-50 border-b border-gray-100 px-4 py-3 flex items-center gap-2">
              <div className="flex gap-1.5">
                <div className="w-2.5 h-2.5 rounded-full bg-red-400" />
                <div className="w-2.5 h-2.5 rounded-full bg-yellow-400" />
                <div className="w-2.5 h-2.5 rounded-full bg-green-400" />
              </div>
              <div className="flex-1 mx-4 h-6 bg-white rounded-md border border-gray-200 flex items-center px-3">
                <span className="text-xs text-gray-400">aidocs-lumoslogic.web.app/dashboard</span>
              </div>
            </div>
            {/* App UI mockup */}
            <div className="flex h-64 bg-gray-50">
              {/* Sidebar */}
              <div className="w-40 border-r border-gray-100 bg-white p-3 flex flex-col gap-2">
                <div className="flex items-center gap-1.5 px-2 py-1.5 rounded-lg" style={{ backgroundColor: `${BRAND}12` }}>
                  <div className="w-3 h-3 rounded" style={{ backgroundColor: BRAND }} />
                  <div className="h-2 w-16 bg-gray-200 rounded-full" />
                </div>
                {[1, 2, 3].map(i => (
                  <div key={i} className="flex items-center gap-1.5 px-2 py-1.5 rounded-lg">
                    <div className="w-3 h-3 rounded bg-gray-200" />
                    <div className="h-2 w-14 bg-gray-100 rounded-full" />
                  </div>
                ))}
              </div>
              {/* Content */}
              <div className="flex-1 p-5 flex flex-col gap-3">
                <div className="flex gap-3">
                  {[
                    { label: 'Total Docs', val: '24' },
                    { label: 'This Month', val: '8' },
                    { label: 'PDFs Sent', val: '16' },
                  ].map((s) => (
                    <div key={s.label} className="bg-white rounded-lg border border-gray-100 p-3 flex-1">
                      <p className="text-[10px] text-gray-400 font-medium">{s.label}</p>
                      <p className="text-lg font-bold text-gray-800 mt-0.5">{s.val}</p>
                    </div>
                  ))}
                </div>
                <div className="bg-white rounded-lg border border-gray-100 flex-1 p-3">
                  <div className="h-2 w-24 bg-gray-100 rounded-full mb-3" />
                  {[1, 2, 3].map(i => (
                    <div key={i} className="flex items-center gap-2 py-1.5 border-b border-gray-50 last:border-0">
                      <div className="h-2 w-24 bg-gray-100 rounded-full" />
                      <div className="h-2 w-16 bg-gray-100 rounded-full" />
                      <div className="h-4 w-14 rounded-md ml-auto" style={{ backgroundColor: `${BRAND}12` }} />
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Social proof logos ────────────────────────── */}
      <section className="py-10 border-y border-gray-100 bg-gray-50/50">
        <div className="max-w-5xl mx-auto px-4">
          <p className="text-center text-xs font-semibold text-gray-400 uppercase tracking-widest mb-7">Powering workflows at</p>
          <div className="flex flex-wrap justify-center items-center gap-10 lg:gap-16 opacity-30 grayscale">
            {['TechCorp', 'LumosLogic', 'WashCure', 'TrueHolidays', 'DocuFlow AI'].map(name => (
              <span key={name} className="text-xl font-black tracking-tighter">{name}</span>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features grid ─────────────────────────────── */}
      <section id="features" className="py-20 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <Pill><Zap size={10} />Features</Pill>
            <h2 className="text-3xl sm:text-4xl font-extrabold mt-3 mb-3 text-gray-900 tracking-tight">
              Everything your business needs
            </h2>
            <p className="text-gray-500 max-w-xl mx-auto text-base">
              From AI generation to PDF delivery — the complete document workflow, built for speed.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <FeatureCard
              icon={Brain}
              title="Gemini 2.5 AI Engine"
              desc="Describe your project in plain English. The AI builds sections, tables, and pricing logic instantly."
              accent
            />
            <FeatureCard
              icon={FileText}
              title="9 Document Types"
              desc="Quotations, invoices, proposals, SOWs, NDAs, agreements, receipts, timelines and more."
            />
            <FeatureCard
              icon={Download}
              title="One-Click PDF Export"
              desc="High-quality Cloudinary-hosted PDFs with your company branding injected automatically."
            />
            <FeatureCard
              icon={History}
              title="Unlimited Version History"
              desc="Every change is tracked. Restore any previous version of a document with a single click."
            />
            <FeatureCard
              icon={Users}
              title="Client CRM"
              desc="Save client contact info, addresses, and tax IDs. Reuse across all documents instantly."
            />
            <FeatureCard
              icon={Lock}
              title="Multi-Tenant Isolation"
              desc="Company-level data isolation. Your documents are only accessible to your team."
            />
            <FeatureCard
              icon={Share2}
              title="Shareable Links"
              desc="Share a read-only document link with clients — no login required on their end."
            />
            <FeatureCard
              icon={PieChart}
              title="Analytics Dashboard"
              desc="Track document volume, type breakdowns, and client activity at a glance."
            />
            <FeatureCard
              icon={Globe}
              title="Custom Branding"
              desc="Logo, address, GST and terms auto-injected across every generated PDF document."
            />
          </div>
        </div>
      </section>

      {/* ── How it works ──────────────────────────────── */}
      <section id="how-it-works" className="py-20 px-4 bg-gray-50">
        <div className="max-w-5xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-14 items-center">
            <div>
              <Pill><Clock size={10} />How it works</Pill>
              <h2 className="text-3xl sm:text-4xl font-extrabold mt-3 mb-4 tracking-tight text-gray-900">
                From brief to PDF in under 30 seconds
              </h2>
              <p className="text-gray-500 mb-8 text-base leading-relaxed">
                No templates to fill, no formatting to fight. Just describe what you need and let the AI handle everything.
              </p>
              <div className="space-y-5">
                <Step n={1} title="Set up your company profile" desc="Add your logo, GST number, and address once. It's injected into every document." />
                <Step n={2} title="Describe your requirements" desc="Type a plain-English brief — scope, client, pricing, terms — anything you'd tell a colleague." />
                <Step n={3} title="AI generates the document" desc="Gemini 2.5 structures sections, builds cost tables, and writes professional copy in seconds." />
                <Step n={4} title="Edit, approve, and share" desc="Fine-tune with AI or manually, then download or share a direct PDF link with your client." />
              </div>
            </div>

            {/* Demo card */}
            <div className="bg-white rounded-2xl border border-gray-100 shadow-lg p-6 space-y-4">
              <div className="flex items-center gap-3 pb-4 border-b border-gray-100">
                <div className="w-9 h-9 rounded-xl flex items-center justify-center text-white text-sm font-bold shrink-0" style={{ backgroundColor: BRAND }}>
                  AI
                </div>
                <div>
                  <p className="text-sm font-semibold text-gray-900">AI is generating...</p>
                  <p className="text-xs text-gray-400">Quotation · LumosLogic</p>
                </div>
                <div className="ml-auto flex gap-1">
                  {[0, 1, 2].map(i => (
                    <div key={i} className="w-1.5 h-1.5 rounded-full animate-bounce" style={{ backgroundColor: BRAND, animationDelay: `${i * 0.15}s` }} />
                  ))}
                </div>
              </div>
              {[
                { label: 'Document Title', value: 'E-Commerce Website Quotation' },
                { label: 'Client', value: 'TechCorp Solutions Pvt Ltd' },
                { label: 'Total Value', value: '₹1,50,000' },
              ].map(({ label, value }) => (
                <div key={label} className="flex justify-between items-center py-1.5 border-b border-gray-50">
                  <span className="text-xs text-gray-400">{label}</span>
                  <span className="text-xs font-semibold text-gray-800">{value}</span>
                </div>
              ))}
              <div className="bg-gray-50 rounded-xl p-4 space-y-2">
                <div className="h-2 w-full bg-gray-200 rounded-full animate-pulse" />
                <div className="h-2 w-4/5 bg-gray-200 rounded-full animate-pulse" />
                <div className="h-2 w-3/5 bg-gray-200 rounded-full animate-pulse" />
              </div>
              <div
                className="w-full py-2.5 rounded-lg text-white text-sm font-semibold text-center flex items-center justify-center gap-2"
                style={{ backgroundColor: BRAND }}
              >
                <Download size={15} />
                Download PDF
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Testimonials ──────────────────────────────── */}
      <section className="py-20 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <Pill><Star size={10} />Testimonials</Pill>
            <h2 className="text-3xl font-extrabold mt-3 tracking-tight text-gray-900">Loved by business owners</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {[
              {
                name: 'Dhruv Shah', company: 'LumosLogic', role: 'Founder',
                text: 'We went from spending 2 hours per quotation to 30 seconds. The AI understands our pricing structure perfectly.',
                avatar: 'DS',
              },
              {
                name: 'Priya Mehta', company: 'TechVision', role: 'Operations Head',
                text: 'The branding automation alone saved our team hours every week. Every PDF looks exactly on-brand.',
                avatar: 'PM',
              },
              {
                name: 'Rohan Verma', company: 'BuildRight', role: 'Sales Manager',
                text: 'Version history is a game-changer. We can track every revision and restore any version instantly.',
                avatar: 'RV',
              },
            ].map(({ name, company, role, text, avatar }) => (
              <div key={name} className="bg-white border border-gray-100 rounded-2xl p-5 shadow-sm">
                <div className="flex gap-0.5 mb-3">
                  {[1, 2, 3, 4, 5].map(i => (
                    <Star key={i} size={13} fill={BRAND} style={{ color: BRAND }} />
                  ))}
                </div>
                <p className="text-sm text-gray-600 leading-relaxed mb-4">"{text}"</p>
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold" style={{ backgroundColor: BRAND }}>
                    {avatar}
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-gray-800">{name}</p>
                    <p className="text-xs text-gray-400">{role}, {company}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pricing ───────────────────────────────────── */}
      <section id="pricing" className="py-20 px-4 bg-gray-50">
        <div className="max-w-3xl mx-auto text-center">
          <Pill>Pricing</Pill>
          <h2 className="text-3xl sm:text-4xl font-extrabold mt-3 mb-3 tracking-tight text-gray-900">Simple, honest pricing</h2>
          <p className="text-gray-500 mb-10">Early adopters get everything free during beta.</p>

          <div className="bg-white border-2 rounded-2xl p-8 shadow-lg relative overflow-hidden text-left" style={{ borderColor: BRAND }}>
            <div className="absolute top-0 right-0 text-white text-xs font-bold px-4 py-1.5 rounded-bl-xl" style={{ backgroundColor: BRAND }}>
              BETA · FREE
            </div>

            <div className="flex items-baseline gap-2 mb-5">
              <span className="text-5xl font-extrabold text-gray-900">₹0</span>
              <span className="text-gray-400 font-medium">/ month</span>
            </div>

            <p className="text-gray-500 text-sm mb-6">Full access for early adopters. No credit card required.</p>

            <ul className="space-y-3 mb-8">
              {[
                'Unlimited AI document generations',
                'All 9 document types',
                'Cloudinary PDF hosting & versioning',
                'Client CRM & product catalog',
                'Custom branding & logo injection',
                'Shareable document links',
                'Version history & restore',
              ].map((item) => (
                <li key={item} className="flex items-center gap-2.5 text-sm text-gray-700">
                  <CheckCircle2 size={16} className="text-green-500 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>

            <Link
              to="/register"
              style={{ backgroundColor: BRAND }}
              className="block w-full py-3 text-white rounded-xl font-semibold text-sm text-center hover:opacity-90 transition-all shadow"
            >
              Create free account
            </Link>
          </div>
        </div>
      </section>

      {/* ── FAQ ───────────────────────────────────────── */}
      <section className="py-20 px-4">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-2xl font-extrabold text-center mb-10 text-gray-900">Frequently asked questions</h2>
          <div className="space-y-4">
            {[
              {
                q: 'Is my data secure?',
                a: 'Yes. We use multi-tenant isolation at the database level via Convex, ensuring your documents are only accessible to your company users.',
              },
              {
                q: 'Which AI model powers generation?',
                a: 'DocuFlow AI uses Google Gemini 2.5 Flash — one of the fastest and most accurate models for structured document generation.',
              },
              {
                q: 'Can I use my own logo and branding?',
                a: 'Absolutely. Upload your logo once in Company Profile and it is automatically injected into every generated PDF.',
              },
              {
                q: 'Can I restore older versions?',
                a: 'Yes. Every update saves a version snapshot. Open any document and navigate to History to view and restore past versions.',
              },
              {
                q: 'Is there a team/multi-user plan?',
                a: 'Multi-user RBAC is on the roadmap. Currently each company account can have one active user. Teams support is coming soon.',
              },
            ].map(({ q, a }) => (
              <div key={q} className="bg-white border border-gray-100 rounded-xl p-5 shadow-sm">
                <p className="font-semibold text-gray-900 text-sm mb-2">{q}</p>
                <p className="text-gray-500 text-sm leading-relaxed">{a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ─────────────────────────────────── */}
      <section className="py-20 px-4">
        <div className="max-w-3xl mx-auto text-center rounded-2xl p-12" style={{ backgroundColor: BRAND }}>
          <h2 className="text-3xl font-extrabold text-white mb-3 tracking-tight">Ready to save hours every week?</h2>
          <p className="text-white/70 mb-8 text-base">Join 2,500+ teams already using DocuFlow AI. Free during beta.</p>
          <Link
            to="/register"
            className="inline-flex items-center gap-2 bg-white font-semibold text-sm px-8 py-3 rounded-xl hover:bg-gray-100 transition-all shadow-lg"
            style={{ color: BRAND }}
          >
            Get started free
            <ArrowRight size={16} />
          </Link>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
};

export default LandingPage;
